name: softi_common
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation:
  location:
  get: 3.25.6
  nested:
  get_storage:
  flutter_secure_storage:
  connectivity:
  flutter_easyloading:
  image_picker:
  image_cropper:
  wechat_camera_picker:
  wechat_assets_picker: 
  
# flutter packages pub run build_runner watch --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  # build_runner:
  # freezed:

flutter: