name: softi_common
description: A new Flutter package project.
version: 2.0.0
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.1.3
  freezed_annotation: ^0.14.1
  location: ^4.1.1
  nested: ^1.0.0
  get_storage: ^2.0.2
  flutter_secure_storage: ^4.1.0
  connectivity: ^3.0.3
  flutter_easyloading: ^3.0.0
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  wechat_camera_picker: ^2.1.1
  wechat_assets_picker: ^5.1.0 
  flutter_form_builder: ^6.0.0-nullsafety.1
  
# flutter packages pub run build_runner watch --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  # build_runner:
  # freezed:

flutter: