name: softi_core_module
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation:
  location:
  recase:
  get:
  get_storage:
  logger:
  merge_map:
  flutter_secure_storage:
  stacked_services:
  connectivity:
  wechat_camera_picker:
  smart_select:

  

# flutter packages pub run build_runner watch --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  build_runner:
  freezed:


flutter:

