name: softi_firebase_services_module
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_functions:
  firebase_dynamic_links:
  firebase_storage:
  firebase_remote_config:
  firebase_messaging:
  firebase_analytics:
  firebase_database:

  softi_common_module:
    path: ../softi_common_module
  
  softi_firebase_auth_module:
    path: ../softi_firebase_auth_module

# flutter packages pub run build_runner watch --delete-conflicting-outputs
# flutter packages pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:

flutter:

