name: softi_form_module
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  softi_core_module:
    path: ../softi_core_module
  
  merge_map:
  flutter_secure_storage:
  flutter_form_builder: 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

