name: softi_services_module
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  connectivity: 
  stacked_services:
  wechat_assets_picker: 
  wechat_camera_picker:
  flutter_easyloading:

  softi_core_module:
    git:
      url: https://b5f960e33e1c7fd9d5425ecfb9ded11dfcf1e7a1@github.com/atoumbre/softi_packages.git
      ref: v0.1
      path: softi_core_module

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
